services:
  - type: web
    name: nexusnet
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
